import React from 'react';
import Header from '../components/Header/index';
import Sidebar from '../components/Sidebar/index';
import { Flex } from '@chakra-ui/react'
import Footer from '../components/Footer';
import Head from 'next/head';

type Props = {
  children: React.ReactNode;
};

const AppLayout: React.FC<Props> = ({ children }) => (
  <>
  <Head>
        <title>RS Lang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dictionary.svg" />
  </Head>
  <Flex width='100%' maxH='100vh'>
    <Sidebar />
      <Flex flexDir='column' justify='space-between' flexGrow='1' maxH='100vh'>
        <Header/>
        <main>{children}</main>
        <Footer />
      </Flex>
  </Flex>
  </>
);

export default AppLayout;
